skillMetadata:
   sections:
      - name: HomeAssistantData
        fields:
          - name: host
            type: text
            label: Url of HA instance
            value: 'kojbito.duckdns.org'
          - name: port
            type: number
            label: Port of HAS instance
            value: 8123
          - name: token
            type: password
            label: Bearer token
            value: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjZDI1NmYzMDgxNzc0YWNjYmVkNzMxM2ZlODk5MzY5ZCIsImlhdCI6MTY3NjkyMzA5MCwiZXhwIjoxOTkyMjgzMDkwfQ.AIy4ellPK-JgVlsIG0O-l_0_ykIjjvPgKFoPueY-czw'
